name: labor-pool-api
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/labor-pool-api.yml'
      - '.eslintrc.js'
      - 'tsconfig.json'
      - 'serverless.yml'
      - 'package.json'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/labor-pool-api.yml'
      - '.eslintrc.js'
      - 'tsconfig.json'
      - 'serverless.yml'
      - 'package.json'
jobs:
  lint_test:
    name: Lint, test, build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build

  deploy:
    name: Deploy
    if: github.actor != 'dependabot[bot]'
    needs: [lint_test]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_GITHUB_ACTIONS_USER }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_GITHUB_ACTIONS_USER }}
          aws-region: us-east-1
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - run: yarn install

      - name: Deploy Dev
        run: yarn deploy-ci:dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_GITHUB_ACTIONS_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_GITHUB_ACTIONS_USER }}

      - name: Deploy Prod
        if: github.ref == 'refs/heads/main'
        run: yarn deploy-ci:prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_GITHUB_ACTIONS_USER }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_GITHUB_ACTIONS_USER }}
